import "./globals.css";
import Header from "./components/layout/header";

import { Sora } from 'next/font/google';

const sora = Sora({
  weight: '400',
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
